(defun hello(name)
    (message "Hello %s" name)
)

(setq names '("Me" "You"))
(mapcar 'hello names)
(message "Added Him to the beginning of the list")
(add-to-list 'names "Him")
(mapcar 'hello names)
(add-to-list 'names "Her" t)
(message "Added Her to the end of the list")
(mapcar (quote hello) names)
(setq names (delete "Her" names))
(message "Removed Her from the list")
(mapcar (quote hello) names)
(message "Added Her to the beginning of the list")
(setq names (cons "Her" names))
(mapcar (quote hello) names)
(message "First in the list is %s" (car names))
(message "The rest of the list is")
(mapcar (quote hello) (cdr names))
